set background=dark
set backspace=indent,eol,start
set backup
set helplang=en
set history=50
set hlsearch
set incsearch
set mouse=a
set ruler
set showcmd
set termencoding=utf-8
set nu
set ts=4
colorscheme vibrantink
syntax on
set nowrap
set autoindent
set smartindent
