set term=tmux-256color
set bg=dark
set backspace=indent,eol,start
set backup
set helplang=en
set history=50
set hlsearch
set incsearch
set ruler
set showcmd
set termencoding=utf-8
set nu
set tabstop=4
set shiftwidth=4
colorscheme inkpot
syntax on
set nowrap
set autoindent
set smartindent
